image: Visual Studio 2019

# Versioning
version: '1.0.{build}'

dotnet_csproj:
  patch: true
  file: 'Directory.Build.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# Install
install:
  - ps: scripts\DisableStrongName.ps1

# Build
build_script:
  - ps: scripts\Build.ps1 -Configuration Release -Pack -AppVeyorLogger

before_build:
  - ps: scripts\RestorePackages.ps1

# Artifacts
artifacts:
  - path: 'PkgOut\*.nupkg'

# Test
test_script:
  - ps: scripts\Test.ps1 -Configuration Release -UploadResultsToAppVeyor
